# Render Blueprint for SkillSwap
# Creates: PostgreSQL (skillswap-db) and Web Service (skillswap-api) using backend/Dockerfile

services:
  - type: web
    name: skillswap-api
    env: docker
    plan: free
    region: oregon
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skillswap-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: skillswap-db
    plan: free
    region: oregon
    databaseName: skillswap
    user: skillswap_user
